---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    name: in-cluster
  source:
    path: manifest
    repoURL: 'https://github.com/robinmordasiewicz/argocd/'
    targetRevision: HEAD
  directory:
  recurse: true
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
