apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
<<<<<<< HEAD:deployment.yaml
          image: robinhoodis/nginx:0.5.3
=======
          image: robinhoodis/nginx-cnf:0.5.7
>>>>>>> 7440dcf9d8d9fcab0fa2f085ac35897a3753e473:nginx-deployment.yaml
          ports:
            - name: http
              containerPort: 80
