apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: docker.io/robinhoodis/jenkins:2.332.1-14
  name: jenkins
  namespace: argocd
  finalizers:
  - "application-finalizer.appsource.argoproj.io"
spec:
  project: default
  source:
    chart: jenkins
    repoURL: 'https://robinmordasiewicz.github.io/helm-charts'
    targetRevision: 3.11.8-78
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: r-mordasiewicz
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
