apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  finalizers:
spec:
  project: default
  source:
    chart: jenkins
    repoURL: 'https://robinmordasiewicz.github.io/helm-charts'
    targetRevision: "3.11.8-176"
    helm:
      valueFiles:
      - custom-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: r-mordasiewicz
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
