apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkinsci
  namespace: argocd
spec:
  project: default
  source:
    chart: jenkinsci/jenkins
    repoURL: https://charts.jenkins.io
    path: jenkins
    targetRevision: latest
    helm:
      releaseName: jenkinsci
  destination:
    server: "https://kubernetes.default.svc"
    namespace: r-mordasiewicz
