apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    chart: jenkins
    repoURL: 'https://github.com/robinmordasiewicz/argocd'
    path: jenkins/
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  destination:
    name: in-cluster
    server: "https://kubernetes.default.svc"
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

