apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    chart: robinmordasiewicz/jenkins
    repoURL: 'https://robinmordasiewicz.github.io/helm-charts'
    targetRevision: 3.11.8
    helm:
      valueFiles:
      - values.yaml
  destination:
    name: in-cluster
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
