apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: "default"
  source:
    repoURL: https://github.com/robinmordasiewicz/argocd.git
    targetRevision: 1.69.9
    path: nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: r-mordasiewicz
  syncPolicy:
    preserveResourcesOnDeletion: false
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
